Command: /home/ziad/.espressif/python_env/idf5.5_py3.10_env/bin/python /home/ziad/esp-idf/tools/idf_monitor.py -p /dev/ttyUSB0 -b 115200 --toolchain-prefix xtensa-esp32-elf- --target esp32 --revision 0 /home/ziad/Ziad_WS/Device_Driver/esp32/esp_cpp/build/CPP_ESP.elf /home/ziad/Ziad_WS/Device_Driver/esp32/esp_cpp/build/bootloader/bootloader.elf -m '/home/ziad/.espressif/python_env/idf5.5_py3.10_env/bin/python' '/home/ziad/esp-idf/tools/idf.py'
[0;33m--- esp-idf-monitor 1.5.0 on /dev/ttyUSB0 115200[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H[0m
[0;33m--- 0x40080400: _invalid_pc_placeholder at /home/ziad/esp-idf/components/xtensa/xtensa_vectors.S:2235
[0m
[0;33m--- 0x40080638: call_start_cpu0 at /home/ziad/esp-idf/components/bootloader/subproject/main/bootloader_start.c:25
[0m
[0;33m--- 0x40080400: _invalid_pc_placeholder at /home/ziad/esp-idf/components/xtensa/xtensa_vectors.S:2235
[0m
[0;33m--- 0x40080638: call_start_cpu0 at /home/ziad/esp-idf/components/bootloader/subproject/main/bootloader_start.c:25
[0m
[1;31m--- Error: device reports readiness to read but returned no data (device disconnected or multiple access on port?)[0m
[0;33m--- Waiting for the device to reconnect[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m[0m
E